version: '3.7'
services:
  mongodb:
    image: mongo:latest
    #environment:
     # MONGO_INITDB_ROOT_USERNAME: root
     # MONGO_INITDB_ROOT_PASSWORD: rootpassword lets fix this later.
    ports:
      - 27017:27017
    networks:
      - www_home
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

networks:
  www_home:
    external: true